name: rust-integration-tests-chainstack
on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_0_6_0_MAINNET_CHAINSTACK }}
        # Start Beerus, then try to reach it. If still unavaible after 120 seconds, make the step fail.
        run: ./target/release/beerus & ./scripts/wait-for-it.sh localhost:3030 -t 120

      - name: run integration test on MAINNET
        env:
          TEST_BACKEND_URL: http://localhost:3030
        run: cargo test --package integration-tests --features enabled

      - name: stop RPC
        run: kill $(lsof -t -i:3030)
 